config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	
	root 'welcome#index'
  get '/login'     => 'sessions#new'
	post '/login'    => 'sessions#create'
	get '/logout' => 'sessions#destroy'
	
	resources :gifs, only: [:index]
  	
  resources :users, only: [:new, :show, :create] do
		resources :favorites, only: [:create, :destroy]
	end
	
	resources :categories, only: [:show] do 
		resources :gifs, only: [:index]
	end 
	
	namespace :admin do
  	resources :categories, except: [:edit, :update]
		resources :gifs, only: [:index, :new, :create, :destroy]
	end
		
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :gifs
  has_many :favorites, through: :gifs
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :gif
  
  def self.favorites_sorted_by_category
    joins(:gif).order('gifs.categories.name')
  end  
end

app/models/gif.rb
class Gif < ApplicationRecord
  validates_presence_of :image_path
  
  belongs_to :category
  has_many :favorites
  has_many :users, through: :favorites
  
  def self.gifs_sorted_by_category
    joins(:category).order('categories.name')
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates_presence_of :name
  validates_presence_of :password
  validates_presence_of :role
  
  has_many :favorites
  has_many :gifs, through: :favorites
  has_secure_password
	
  enum role: ['default', 'admin']
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: '/public/404' unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  
  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    category = Category.new(category_params)
    if category.save
      redirect_to admin_categories_path
      flash[:notice] = "Category #{category.name} successfully created!"
    else
      flash[:alert] = "Didn't work, try again."
      redirect_to new_admin_category_path
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    redirect_to admin_categories_path
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end 

app/controllers/admin/gifs_controller.rb
class Admin::GifsController < ApplicationController
  
  def new
    @gifs = Gif.new
  end

  def create
    gif = Gif.new(gif_params)
    if gif.save
      flash[:notice] = "Successfully created Gif!"
      redirect_to admin_gifs_path
    else
      flash[:alert] = "Didn't work, try again!"
      redirect_to new_admin_gif_path
    end
  end
  
  def destroy
    gif = Gif.find(params[:id])
    gif.destroy
    redirect_to admin_gifs_path
  end
  
  private

    def gif_params
      params.require(:gif).permit(:image_path)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :current_admin?
 
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def current_admin?
    current_user && current_user.admin?
  end
    
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    @favorite = Favorite.create(favorite_params)
    redirect_to user_path(params[:user_id])
  end
  
  def destroy
    favorite = Favorite.find(params[:id])
    favorite.destroy
    redirect_to user_path(params[:user_id])
  end
  
  private 
    def favorite_params 
      params.require(:favorite).permit(:user_id, :gif_id)
    end
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController

  def index 
    @catergories = Category.all
    @gifs = Gif.gifs_sorted_by_category
    @gifs_slices = @gifs.all.each_slice(4)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    @user = User.find_by(email: params[:email].downcase)
    if @user && @user.authenticate(params[:password]) 
      session[:user_id] = @user.id
      redirect_to gifs_path, notice: 'Successfully logged in!'
    else
      flash.now.alert = 'Incorrect email or password, try again!'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: 'You have been successfully logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: params[:id])
    @favorites_slices = favorites.each_slice(4)
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    @user.email.downcase!
    if @user.save
      session[:user_id] = @user.id 
      redirect_to user_path(@user)
      flash[:notice] = "Successfully created account for #{@user.name}!"
    else
      flash[:alert] = 'Oops, could not create account. Please use a valid email and password and try again.'
      render :new
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h1>All Categories</h1>

<%= link_to "Create A New Category", new_admin_category_path %>

<% @categories.each do |category| %>
  <p>
    <%= link_to category.name, admin_category_path(category) %>
    <%= link_to "Delete", admin_category_path(category), method: :delete %>
  </p>
<% end %>

app/views/admin/categories/new.html.erb
<h1>Create a New Category</h1>

<%= form_for([:admin, @category]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit "Search" %>
<% end %>

app/views/admin/categories/show.html.erb
<h1><%= @category.name %> Gifs </h1>

<%= link_to "Create A New Gif", new_admin_gif_path %>

<% @category.gifs.each do |gif|  %>
  <%=link_to image_tag(category.gif.image_path, size: "337x500", id: "image_#{category.gif.id}") %>
  <%= link_to "Delete", admin_gif_path(gif), method: :delete %>
<% end %>

app/views/admin/gifs/index.html.erb
<h1> All Gifs </h1> 

<%= link_to "Create A New Gif", new_admin_gif_path %>

<% @gifs.each do |gif| %>
  <%= gif.category.name %>
  <%= link_to image_tag(gif.image_path, size: '337x500', id: "image_#{gif.id}"), gif_path(gif) %>
  <%= link_to "Delete", admin_gif_path(gif), method: :delete %>
<% end %>

app/views/admin/gifs/new.html.erb
<h1>Create A New Gif</h1>

<%= form_for([:admin, @gif]) do |f| %>
  <%= f.label :image_path %>
  <%= f.file_field :image_path %>

  <%= f.submit %>
<% end %>

app/views/gifs/index.html.erb
<div>
  <h1 class="display-6 text-center"> All Gifs </h1>
  </br>
  <h4 class="display-10 text-center"> <%= link_to 'This way to Your Favorite Gifs', user_path(current_user) %>
</div>
</br>

<% @gifs_slices.each do |group| %>
  <div class="card-deck">
    <% group.each do |gif| %>
      <div class="card" size:"300x500" background:"#E0FFFF;">
        <%=link_to image_tag(gif.image_path, size: "337x500", id: "image_#{gif.id}")%>
        <div class="card-body">
          <p class="card-text"><%= gif.category.name %></p>
          </br>
          <% if current_user %>
            <p class="card_form"><%= form_for current_user.favorites.new, url: user_favorites_path(current_user) do |f| %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.hidden_field :gif_id, value: gif.id  %>
              <%= f.submit 'Add Gif To Your Favorites' %>
            <% end %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  </br>
<% end %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title> Gif-Generator </title>
  
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>  
    
    <style>
      body {
            background: #FFFFFF;
            font-color
            }
    </style>
  </head>
  
  <body>
    <nav class="navbar sticky-top navbar navbar-dark bg-primary text_inline">
    <a class="navbar-brand" href="/">
      <img src="https://i.kym-cdn.com/photos/images/newsfeed/000/328/752/fdc.gif" width="50" height="50" class="d-inline-block align-top" alt="">
      Gif Generator
    </a>
    <ul class="navbar-nav">
      <% if current_user %>
        <li class="nav-item">
          <a><%= "Logged in as #{current_user.name}" %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/logout">Log Out</a>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link" href="/login">Log In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/new">Sign Up</a>
        </li>
      <% end %>
    </ul>
    </nav>
    <hr>
    <% if notice %>
      <%= notice %>
    <% end %>

    <% if alert %>
        <%= alert %>
    <% end %>
	
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1> Please Sign Up </h1>

<%= form_for @user do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>


  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<div>
  <h1 class="display-6 text-center"> Your Favorite Gifs </h1>
  </br>
  <h4 class="display-10 text-center"> <%= link_to 'This way to all Gifs', gifs_path %>
</div>
</br>

<% @favorites_slices.each do |group| %>
  <div class="card-deck">
    <% group.each do |favorite| %>
      <div class="card" size:"300x500" background:"#E0FFFF;">
        <%=link_to image_tag(favorite.gif.image_path, size: "337x500", id: "image_#{favorite.gif.id}")%>
        <div class="card-body">
        <h4><p class="card-text"><%= favorite.gif.category.name %></p></h4>
          <p><%= link_to 'Unfavorite Gif', user_favorite_path(current_user, favorite), method: :delete %></p>
          </br>
        </div>
      </div>
    <% end %>
  </div>
  </br>
<% end %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Gif it a Chance!</h1>
  <p class="lead"> Welcome, Gif Generator allows you to see the Gifs you want and have them saved as your favorites, so that you can always get back to them when ever you are ready! Gif it a Chance and become a user today. All that is required is a quick sign up and you are ready to Gif all day long. </p>
  <hr class="my-4">
  <p>Please sign up to create your user account or log in if you already have an account.</p>
  <a class="btn btn-primary btn-lg" href="/users/new" role="button">Sign Up</a>
  <a class="btn btn-primary btn-lg" href="/login" role="button">Log In</a>  
</div>